Django/Django/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import record_view
from . import myRate_view
from . import doctorInfo_view
from . import myDoctor_view
from . import healthControl_view
from . import inquiry_view
from . import doctorList_view
from . import login1_register1_view
from . import interlocution_view
from . import newOld_view
from . import accessDetails_view
from . import terminal_view
from . import area_view
from . import pul_view
from . import general_view
from . import userList_view
from . import classifiedQuery_view
from . import distinguish_view
from . import relationQuery_view
from . import entity_view
from . import search_view
from . import entityQuery_view
from . import baike_view
from . import consoles_view
from . import console_view
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('views/console/', console_view.console),
    path('views/consoles/', consoles_view.consoles),
    path('views/consoles/baike/', baike_view.baike),
    path('views/distinguish/', distinguish_view.distinguish),
    path('views/distinguish/getDistinguishData/', distinguish_view.getDistinguishData),
    path('views/distinguish/baike', baike_view.baike),
    path('views/entityQuery/', entityQuery_view.entityQuery),
    path('views/entityQuery/search/', search_view.search),
    path('views/entityQuery/search/entity/', entity_view.entity),
    path('views/relationQuery/', relationQuery_view.relationQuery),
    path('views/relationQuery/relation/', relationQuery_view.getRelation),
    path('views/relationQuery/node/', relationQuery_view.getNode),
    path('views/relationQuery/nodeRelation/', relationQuery_view.getNodeRelation),
    path('views/relationQuery/baike/', baike_view.baike),
    path('views/classifiedQuery/', classifiedQuery_view.classifiedQuery),
    path('views/classifiedQuery/getFenlei/', classifiedQuery_view.getFenlei),
    path('views/classifiedQuery/getEntity/', classifiedQuery_view.getEntity),
    path('views/classifiedQuery/baike/', baike_view.baike),
    path('views/interlocution/', interlocution_view.interlocution),
    path('views/interlocution/getDoctor/', interlocution_view.getDoctor),
    path('views/myDoctor/', myDoctor_view.myDoctor),
    path('views/myDoctor/setHelper/', myDoctor_view.setHelper),
    path('views/myDoctor/getMyRate/', myDoctor_view.getMyRate),
    path('views/myDoctor/pingjia/', myDoctor_view.pingjia),
    path('views/myDoctor/setPingjia/', myDoctor_view.setPingjia),
    path('views/myRate/', myRate_view.getRate),
    path('views/myRate/setMoney/', myRate_view.setMoney),
    # path('getAnswer/', interlocution_view.getAnswer),
    # re_path('views/(?P<p>\S*)/', views.pages),
    path('admin_views/userList/', userList_view.getAllUser),
    path('admin_views/userList/getUserInfo/', userList_view.getUserInfo),
    path('admin_views/userList/batchDel/', userList_view.batchdel),
    path('admin_views/userList/del/', userList_view.delById),
    path('admin_views/doctorList/', doctorList_view.getAllDoctor),
    path('admin_views/doctorList/getDoctorInfo/', doctorList_view.getDoctorInfo),
    path('admin_views/doctorList/shenhe/', doctorList_view.shenhe),
    path('admin_views/doctorList/updateAuditing/', doctorList_view.updateAuditing),
    path('admin_views/doctorList/del/', doctorList_view.delDoctor),
    path('admin_views/doctorList/batchDel/', doctorList_view.batchDelDoctor),
    path('admin_views/general/', general_view.general),
    path('admin_views/general/getCpuAndMemory/', general_view.getCpuAndMemory),
    path('admin_views/pul/', pul_view.pul),
    path('admin_views/pul/getPulData/', pul_view.getPulData),
    path('admin_views/area/', area_view.area),
    path('admin_views/area/getMapData/', area_view.getMapData),
    path('admin_views/terminal/', terminal_view.getTerminal),
    path('admin_views/terminal/getTerminalData/', terminal_view.getTerminalData),
    path('admin_views/accessDetails/', accessDetails_view.getAccessDetails),
    path('admin_views/accessDetails/getTableData/', accessDetails_view.getTableData),
    path('searchCondition/', views.searchCondition),
    path('admin_views/newOld/', newOld_view.newOld),
    path('admin_views/newOld/getNewOldData/', newOld_view.getNewOldData),
    path('admin_views/record/', record_view.record),
    path('doctor/login1/', login1_register1_view.login),
    path('doctor/getLogin/', login1_register1_view.getLogin),
    path('doctor/register1/', login1_register1_view.register),
    path('doctor/getRegister/', login1_register1_view.getRegister),
    path('doctor/perfectInfo/', login1_register1_view.perfectInfo),
    path('doctor/upload/', login1_register1_view.upload),
    path('doctor/uploadpaper/', login1_register1_view.uploadpaper),
    path('doctor/getPerfectInfo/', login1_register1_view.getPerfectInfo),
    path('doctor/index/', login1_register1_view.index),
    path('doctor/inquiry/', inquiry_view.inquiry),
    path('doctor/inquiry/setAnswerQiuzhu/', inquiry_view.setAnswerQiuzhu),
    path('doctor/healthControl/', healthControl_view.healthControl),
    path('doctor/doctorInfo/', doctorInfo_view.doctorInfo),
    path('doctor/updateDoctorInfo/', doctorInfo_view.updateDoctorInfo),
    path('doctor/uploadPass/', doctorInfo_view.uploadPass),
    path('doctor/uploadPassword/', doctorInfo_view.uploadPassword),
    path('doctor/logout/', doctorInfo_view.logout),
    path('doctor/getQiuzhu/', myDoctor_view.getQiuzhu),
    path('doctor/getQiuzhu1/', inquiry_view.getQiuzhu1),
    path('doctor/getDoctorAndPingjia/', myDoctor_view.getDoctorAndPingjia),
    path('getChatLog/', myDoctor_view.getChatLog),
    path('ManualAnnotation/', include('ManualAnnotation.urls', namespace='ManualAnnotation')),
    path('accounts/', include('users.urls', namespace='users')),
]
# handler400 = views.bad_request
# handler403 = views.permission_denied
# handler404 = views.page_not_found
# handler500 = views.page_error

Django/apps/users/urls.py
from django.urls import path, re_path

from . import views

# 正在部署的应用的名称
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    re_path(r'^userinfo/(?P<pk>\d+)/$', views.userinfo, name='userinfo'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, name='pwd_change'),
    path('logout/', views.logout, name='logout'),
    path('upload/', views.upload, name='upload'),
    path('editUserInfo/', views.edit_userinfo, name='edit_userinfo'),
    path('addUser/', views.adduser, name='adduser'),
    path('updateUser/', views.updateuser, name='updateuser')
]

Django/apps/users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):

    """
    username：用户名
    email: 电子邮件
    password：密码
    first_name：名
    last_name：姓
    is_active: 是否为活跃用户。默认是True
    is_staff: 是否为员工。默认是False
    is_superuser: 是否为管理员。默认是False
    date_joined: 加入日期。系统自动生成。
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # org = models.CharField('Organization', max_length=128, blank=True)
    image = models.CharField(
        max_length=100, default='/static/images/default.gif', verbose_name='头像')
    gender = models.CharField(
        max_length=6, choices=(('male', '男'), ('female', '女')), default='female', verbose_name='性别')
    phone = models.CharField('Phone', max_length=50, blank=True)
    mod_date = models.DateTimeField('Last modified', auto_now=True)

    class Meta:
        verbose_name = 'User Profile'

    def __str__(self):
        return self.user.__str__()

Django/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
import re


def email_check(email):
    pattern = re.compile(r"\"?([-_a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class RegistrationForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=50,
                               widget=forms.TextInput(attrs={
                                   'class': "layui-input admin-input admin-input-username",
                                   'autocomplete': "off",
                                   'placeholder': u'请输入用户名'}), )
    email = forms.EmailField(label='邮箱',
                             widget=forms.TextInput(attrs={
                                 'class': "layui-input admin-input",
                                 'autocomplete': "off",
                                 'placeholder': u'请输入邮箱'}), )
    password1 = forms.CharField(label='密码',
                                widget=forms.PasswordInput(attrs={
                                    'class': "layui-input admin-input",
                                    'autocomplete': "off",
                                    'placeholder': u'请输入密码'}), )
    password2 = forms.CharField(label='再次输入密码',
                                widget=forms.PasswordInput(attrs={
                                    'class': "layui-input admin-input admin-input-verify",
                                    'autocomplete': "off",
                                    'placeholder': u'请再次输入密码'}), )

    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 3:
            raise forms.ValidationError("长度不得小于3！")
        elif len(username) > 50:
            raise forms.ValidationError("长度不得大于50！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("用户名已存在！")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("该邮箱已被注册！")
        else:
            raise forms.ValidationError("请输入有效的邮箱！")

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("密码不得小于6位！")
        elif len(password1) > 20:
            raise forms.ValidationError("密码不得大于20位！")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("密码验证不通过，请重新输入！")

        return password2


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50,
                               widget=forms.TextInput(attrs={
                                   'class': "layui-input admin-input admin-input-username",
                                   'autocomplete': "off",
                                   'placeholder': u'请输入用户名或邮箱'}), )
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={
                                   'class': "layui-input admin-input",
                                   'autocomplete': "off",
                                   'placeholder': u'请输入密码'}), )

    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError("该邮箱未注册！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                raise forms.ValidationError("用户名不存在！")

        return username


class UserinfoForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=50, required=False,
                               widget=forms.TextInput(attrs={
                                   'class': "layui-input",
                                   'readonly': "readonly"}), )
    gender = forms.CharField(max_length=6, required=False,
                             widget=forms.Select(
                                 choices=(('male', u'男'), ('female', u'女')),
                                 attrs={
                                     'class': "layui-input-block"
                                 }))
    image = forms.CharField(max_length=100, required=False,
                            widget=forms.TextInput(attrs={
                                'lay-verify': "required",
                                'id': "LAY_avatarSrc",
                                'placeholder': "图片地址",
                                'class': "layui-input",
                                'readonly': "readonly"
                            }))
    phone = forms.CharField(label='手机', max_length=50, required=False,
                            widget=forms.TextInput(attrs={
                                'class': "layui-input",
                                'autocomplete': "off"}), )
    email = forms.EmailField(label='邮箱', required=False,
                             widget=forms.TextInput(attrs={
                                 'class': "layui-input",
                                 'autocomplete': "off"}), )


class PwdChangeForm(forms.Form):
    old_password = forms.CharField(label='Old password',
                                   widget=forms.PasswordInput(attrs={
                                       'lay-verify': "required",
                                       'class': "layui-input"
                                   }))

    password1 = forms.CharField(label='New Password',
                                widget=forms.PasswordInput(attrs={
                                    'lay-verify': "pass",
                                    'autocomplete': "off",
                                    'class': "layui-input"
                                }))
    password2 = forms.CharField(label='Password Confirmation',
                                widget=forms.PasswordInput(attrs={
                                    'lay-verify': "repass",
                                    'autocomplete': "off",
                                    'class': "layui-input"
                                }))

    # Use clean methods to define custom validation rules

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("密码不得小于6位！")
        elif len(password1) > 20:
            raise forms.ValidationError("密码不得大于20位！")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')

        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("密码验证未通过，请重试！")

        return password2

Django/apps/users/templates/users/edit_userinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>编辑用户</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="../../../../static/users/css/layui.css" media="all">
</head>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-useradmin" id="layuiadmin-form-useradmin" style="padding: 20px 0 0 0;">
    <div class="layui-form-item">
        <input name="id" readonly hidden value="{{ data.id }}">
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">用户名</label>
        <div class="layui-input-inline">
            {% if flag %}
            <input type="text" name="username" value="{{ data.username }}" lay-verify="required" placeholder="请输入用户名" autocomplete="off" class="layui-input">
            {% else %}
            <input type="text" name="username" value="{{ data.username }}" readonly lay-verify="required" placeholder="请输入用户名" autocomplete="off" class="layui-input">
            {% endif %}
        </div>
        <div class="layui-form-mid layui-word-aux">不要随便修改！</div>
    </div>
    {% if flag %}
    <div class="layui-form-item">
        <label class="layui-form-label">密码</label>
        <div class="layui-input-inline">
            <input type="password" name="password" lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input">
        </div>
    </div>
    {% endif %}
    <div class="layui-form-item">
        <label class="layui-form-label">手机号码</label>
        <div class="layui-input-inline">
            <input type="text" name="phone" value="{{ data.phone }}" lay-verify="phone" placeholder="请输入号码" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">邮箱</label>
        <div class="layui-input-inline">
            <input type="text" name="email" value="{{ data.email }}" lay-verify="email" placeholder="请输入邮箱" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item" lay-filter="sex">
        <label class="layui-form-label">选择性别</label>
        <div class="layui-input-block">
            {% ifequal data.sex 'male' %}
            <input type="radio" name="sex" value="male" title="男" checked>
            <input type="radio" name="sex" value="female" title="女">
            {% else %}
            <input type="radio" name="sex" value="male" title="男">
            <input type="radio" name="sex" value="female" title="女" checked>
            {% endifequal %}
        </div>
    </div>
    <div class="layui-form-item layui-hide">
        <input type="button" lay-submit lay-filter="LAY-user-front-submit" id="LAY-user-front-submit" value="确认">
    </div>
</div>
<div id="code" hidden>{{ code }}</div>
<div id="msg" hidden>{{ msg }}</div>
<script src="../../../../static/users/js/layui.js"></script>
<script>
    layui.use(['form', 'upload'], function(){
        var $ = layui.$,
            form = layui.form;

        if ($("#code").text() === '500') {
            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
            parent.layer.close(index); //再执行关闭
            parent.layer.msg($("#msg").text());
        }

    })
</script>
</body>

</html>

Django/apps/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
    <link rel="stylesheet" href="../../static/users/css/layui.css">
    <link rel="stylesheet" href="../../static/users/css/admin.css">
</head>

<style>
    .code{
        background-image: url(code.jpg);
        font-family: Arial;
        font-style: italic;
        color: blue;
        border: 0;
        padding: 2px 3px;
        letter-spacing: 3px;
        font-weight: bolder;
        font-size: 18px;
    }
</style>

<body style="width: 100%; height: 100%;" onload="createCode()">

<div id="container">
    <div class="bg bg-blur" style="height: 100%; position: absolute;"></div>
    <div class="admin-login-background form-wrapper">
        <!--<div class="admin-header">-->
            <!--<img src="http://pic15.nipic.com/20110715/7943290_155206295348_2.jpg" class="admin-logo">-->
        <!--</div>-->
        <span id="message" hidden>{% if message %}{{ message }}{% endif %}</span>
        <form class="layui-form" method="post" action="" enctype="multipart/form-data" onSubmit="return code1()">
            {% csrf_token %}
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-username admin-icon admin-icon-username"></i>
                {{ form.username }}
                <span id="usernameerror" hidden>{{ form.username.errors }}</span>
            </div>
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-password admin-icon admin-icon-password"></i>
                {{ form.password }}
                <span id="passworderror" hidden>{{ form.password.errors }}</span>
            </div>
            <div>
                <div style="width:80px;position: absolute;right: 10px;margin-top: 15px;">
                    <a onClick="createCode()"><span id="login_code" title="看不清，换一张"></span></a>
                </div>
                <div>
                    <input type="text" id="code" name="code" placeholder="验证码" maxlength="6"
                           class="layui-input admin-input admin-input-verify">
                </div>
            </div>
            <div class="button-wrapper submit">
                <button class="layui-btn admin-button" lay-submit>登陆</button>
            </div>
        </form>
        <div style="margin-top: 20px;">
            <a href="javascript:void(0);" style="color: #009688; float: right;">忘记密码？</a>
            <a href="/accounts/register" style="color: #009688;">新用户注册</a>
        </div>
    </div>
</div>
<script src="../../static/users/js/layui.js"></script>
<script>
    layui.use('layer', function () {
        var layer = layui.layer;
        var $ = layui.$;

        if ($("#usernameerror").html() !== '') {
            layer.tips($("#usernameerror").html(), '#id_username', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

        if ($("#passworderror").html() !== '') {
            layer.tips($("#passworderror").html(), '#id_password', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

        if ($("#message").html() !== '') {
            layer.msg($("#message").html(),{
                anim: 6
            });
        }

        $(function(){
            //session过期自动检测，如果当前框架不是顶层，则将顶层设置为此页面
            if(window !== top){
                top.location.href = location.href;
            }
        });

        /****************生成验证码*******************/
        var code;
        window.createCode = function () {
            code = "";
            var codeLength = 5; //验证码的长度
            var checkCode = document.getElementById("login_code");
            var codeChars = new Array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
            'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
            'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'); //所有候选组成验证码的字符，当然也可以用中文的
            for(var i = 0; i < codeLength; i++){
                var charNum = Math.floor(Math.random() * 52);
                code += codeChars[charNum];
            }
            if(checkCode){
                checkCode.className = "code";
                checkCode.innerHTML = code;
            }
        };
        //验证
        window.code1 = function () {
            var inputCode=document.getElementById("code").value;
            if(inputCode.length <= 0){
                layer.msg("请输入验证码！");
                return false;
            }else if(inputCode.toUpperCase() !== code.toUpperCase()){
                createCode();
                layer.msg("验证码输入有误！");
                return false;
            }else{
                return true;
            }
        }

    })
</script>
</body>
</html>

Django/apps/users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="../../static/users/css/layui.css">
    <link rel="stylesheet" href="../../static/users/css/admin.css">
</head>
<body style="width: 100%; height: 100%;">

<div id="container">
    <div class="bg bg-blur" style="height: 100%; position: absolute;"></div>
    <div class="admin-login-background form-wrapper">
        <!--<div class="admin-header">-->
        <!--<img src="images/ex_logo.png" class="admin-logo">-->
        <!--</div>-->
        <form class="layui-form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-username admin-icon admin-icon-username"></i>
                {{ form.username }}
                <span id="usernameerror" hidden>{{ form.username.errors }}</span>
            </div>
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-release admin-icon admin-icon-email"></i>
                {{ form.email }}
                <span id="emailerror" hidden>{{ form.email.errors }}</span>
            </div>
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-password admin-icon admin-icon-password"></i>
                {{ form.password1 }}
                <span id="password1error" hidden>{{ form.password1.errors }}</span>
            </div>
            <div class="fieldWrapper">
                <i class="layui-icon layui-icon-password admin-icon admin-icon-password"></i>
                {{ form.password2 }}
                <span id="password2error" hidden>{{ form.password2.errors }}</span>
            </div>
            <div class="button-wrapper submit">
                <button class="layui-btn admin-button" lay-submit>注册</button>
            </div>
        </form>
        <div style="margin-top: 20px;">
            <a href="/accounts/login" style="color: #009688; float: right;">已有账号？登陆</a>
        </div>
    </div>
</div>
<script src="../../static/users/js/layui.js"></script>
<script>
    layui.use('layer', function () {
        var layer = layui.layer;
        var $ = layui.$;

        $(function(){
            //session过期自动检测，如果当前框架不是顶层，则将顶层设置为此页面
            if(window !== top){
                top.location.href = location.href;
            }
        });

        if ($("#usernameerror").html() !== '') {
            layer.tips($("#usernameerror").html(), '#id_username', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

        if ($("#emailerror").html() !== '') {
            layer.tips($("#emailerror").html(), '#id_email', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

        if ($("#password1error").html() !== '') {
            layer.tips($("#password1error").html(), '#id_password1', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

        if ($("#password2error").html() !== '') {
            layer.tips($("#password2error").html(), '#id_password2', {
                tips: [2, '#FF5722'],
                tipsMore: true
            });
        }

    })
</script>
</body>
</html>

Django/apps/users/templates/users/userinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>设置我的资料</title>
    <link rel="stylesheet" href="../../../../static/users/css/layui.css">
    <link rel="stylesheet" href="../../../../static/users/css/user.css">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">设置我的资料</div>
                <div class="layui-card-body form-wrapper" pad15>

                    <form class="layui-form" method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户名</label>
                            <div class="layui-input-inline fieldWrapper">
                                {{ form.username }}
                            </div>
                            <div class="layui-form-mid layui-word-aux">不可修改。一般用于后台登入名</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">性别</label>
                            <div class="layui-input-inline fieldWrapper">
                                {{ form.gender }}
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">头像</label>
                            <div class="layui-input-inline fieldWrapper">
                                {{ form.image }}
                            </div>
                            <div class="layui-input-inline layui-btn-container" style="width: auto;">
                                <button type="button" class="layui-btn layui-btn-primary" id="LAY_avatarUpload">
                                    <i class="layui-icon">&#xe67c;</i>上传图片
                                </button>
                                <a class="layui-btn layui-btn-primary" onclick="avartatPreview()">查看图片</a >
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">手机</label>
                            <div class="layui-input-inline fieldWrapper">
                                {{ form.phone }}
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">邮箱</label>
                            <div class="layui-input-inline fieldWrapper">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block button-wrapper submit">
                                <button class="layui-btn" lay-submit>确认修改</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重新填写</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% csrf_token %}
<script src="../../../../static/users/js/layui.js"></script>
<script>
    layui.use(['form', 'upload'], function () {
        var n = layui.form;
        var i = layui.$, e = layui.layer, s = layui.upload;
        var r = i("#LAY_avatarSrc");
        var formData = new FormData();
        var csrfToken = i("[name='csrfmiddlewaretoken']").val();
        // formData.append('avatar', i("#id_image").get(0).files[0]);
        s.render({
            url: "/accounts/upload/",
            headers: {"X-CSRFToken": csrfToken},
            elem: "#LAY_avatarUpload",
            accept: 'images',
            done: function (t) {
                // console.log(t);
                0 === t.code ? (r.val(t.data.src) && e.msg(t.msg)) : e.msg(t.msg, {icon: 5})
            }
        });
        window.avartatPreview = function () {
            var i = r.val();
            //获取第二个/出现的位置
            // var index = find(i,'/',1);
            // var url = i.substring(index);
            e.photos({photos: {title: "查看头像", data: [{src: i}]}, shade: .01, closeBtn: 1, anim: 5})
        };

        //查找字符在字符串中的位置
        // function find(str, cha, num){
        //     var x = str.indexOf(cha);
        //     for(var i = 0; i < num; i++){
        //         x=str.indexOf(cha, x + 1);
        //     }
        //     return x;
        // }
    })
</script>
</body>

</html>